export const PROPERTY_IMAGE_MAX_MB = 50;
export const PROPERTY_DOCUMENT_MAX_MB = 50;
export const PROPERTY_WALKTHROUGH_MAX_MB = 15;

export const PROPERTY_IMAGE_MAX_BYTES = PROPERTY_IMAGE_MAX_MB * 1024 * 1024;
export const PROPERTY_DOCUMENT_MAX_BYTES = PROPERTY_DOCUMENT_MAX_MB * 1024 * 1024;
export const PROPERTY_WALKTHROUGH_MAX_BYTES = PROPERTY_WALKTHROUGH_MAX_MB * 1024 * 1024;
