import type { CommercialDetails, PossessionDetails } from "@/components/acres/mock-data";

type Props = { details: CommercialDetails; setDetails: (value: CommercialDetails) => void; possession: PossessionDetails; setPossession: (value: PossessionDetails) => void; errors: Record<string, string> };
const Input = ({ label, value, onChange, type = "text", error }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; error?: string }) => <label className="block text-[13px] font-semibold text-[#3F3D46]">{label}<input type={type} value={value} min={type === "number" ? 0 : undefined} onChange={(event) => onChange(event.target.value)} className="w-full mt-1 px-3 py-2.5 border border-[#E4E0E7] rounded-lg font-normal" />{error && <p className="text-red-600 text-[11px] mt-1">{error}</p>}</label>;

export default function CommercialDetailsFields({ details, setDetails, possession, setPossession, errors }: Props) {
  const update = (updates: Partial<CommercialDetails>) => setDetails({ ...details, ...updates });
  const officeLike = details.commercialSubtype === "Office Space" || details.commercialSubtype === "Co-working";
  const choosePossession = (status: "Ready to Move" | "Under Construction") => setPossession(status === "Under Construction" ? { status, expectedCompletionDate: "" } : { status, launchDate: "" });
  return <div className="space-y-6">
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      <label className="block text-[13px] font-semibold text-[#3F3D46]">Commercial subtype <select value={details.commercialSubtype} onChange={(event) => update({ commercialSubtype: event.target.value as CommercialDetails["commercialSubtype"] })} className="w-full mt-1 px-3 py-2.5 border border-[#E4E0E7] rounded-lg bg-white font-normal">{["Office Space", "Shop/Showroom", "Warehouse", "Industrial Shed", "Co-working"].map((value) => <option key={value}>{value}</option>)}</select></label>
      <label className="block text-[13px] font-semibold text-[#3F3D46]">Zone type <select value={details.zoneType} onChange={(event) => update({ zoneType: event.target.value as CommercialDetails["zoneType"] })} className="w-full mt-1 px-3 py-2.5 border border-[#E4E0E7] rounded-lg bg-white font-normal">{["IT/ITES SEZ", "Non-SEZ", "Retail", "Industrial"].map((value) => <option key={value}>{value}</option>)}</select></label>
    </div>
    <div className="rounded-2xl border border-[#E4E0E7] p-5 space-y-3"><h3 className="font-bold text-[#121B35]">Area, price & floor</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Input label="Carpet area" value={details.carpetArea || ""} onChange={(value) => update({ carpetArea: value })} error={errors.carpetArea} /><Input label="Built-up area" value={details.builtUpArea || ""} onChange={(value) => update({ builtUpArea: value })} error={errors.builtUpArea} /><Input label="Super area" value={details.superArea || ""} onChange={(value) => update({ superArea: value })} error={errors.superArea} /></div>{errors.areas && <p className="text-red-600 text-[11px]">{errors.areas}</p>}<div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Input label="Floor" value={details.floor} onChange={(value) => update({ floor: value })} error={errors.floor} /><Input label="Total floors" type="number" value={details.totalFloors || ""} onChange={(value) => update({ totalFloors: Number(value) })} error={errors.totalFloors} /></div></div>
    {details.commercialSubtype === "Shop/Showroom" && <Input label="Frontage (main-road frontage)" value={details.frontage || ""} onChange={(value) => update({ frontage: value })} error={errors.frontage} />}
    {officeLike && <div className="rounded-2xl border border-[#E4E0E7] p-5"><h3 className="font-bold text-[#121B35] mb-3">Office capacity</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Input label="Seating capacity" type="number" value={details.seatingCapacity} onChange={(value) => update({ seatingCapacity: Number(value) })} /><Input label="Cabins" type="number" value={details.cabins} onChange={(value) => update({ cabins: Number(value) })} /><Input label="Meeting rooms" type="number" value={details.meetingRooms} onChange={(value) => update({ meetingRooms: Number(value) })} /></div></div>}
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><label className="text-[13px] font-semibold text-[#3F3D46]">Building grade<select value={details.buildingGrade} onChange={(event) => update({ buildingGrade: event.target.value as CommercialDetails["buildingGrade"] })} className="w-full mt-1 px-3 py-2.5 border border-[#E4E0E7] rounded-lg bg-white font-normal">{["Grade A", "Grade B", "Grade C", "Not Applicable"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-[13px] font-semibold text-[#3F3D46]">Pantry<select value={details.pantry} onChange={(event) => update({ pantry: event.target.value as CommercialDetails["pantry"] })} className="w-full mt-1 px-3 py-2.5 border border-[#E4E0E7] rounded-lg bg-white font-normal">{["None", "Shared Pantry", "Private Pantry"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-[13px] font-semibold text-[#3F3D46]">Furnishing<select value={details.furnishing} onChange={(event) => update({ furnishing: event.target.value as CommercialDetails["furnishing"] })} className="w-full mt-1 px-3 py-2.5 border border-[#E4E0E7] rounded-lg bg-white font-normal">{["Bare Shell", "Warm Shell", "Fully Furnished"].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Input label="Structure" value={details.structure || ""} onChange={(value) => update({ structure: value })} /><Input label="Washrooms" value={details.washrooms || ""} onChange={(value) => update({ washrooms: value })} /><Input label="Parking" value={details.parking || ""} onChange={(value) => update({ parking: value })} /><Input label="Power backup" value={details.powerBackup || ""} onChange={(value) => update({ powerBackup: value })} /><Input label="Sanctioned load (KVA)" type="number" value={details.sanctionedLoadKva} onChange={(value) => update({ sanctionedLoadKva: Number(value) })} /><Input label="Fire safety compliance" value={details.fireSafetyCompliance || ""} onChange={(value) => update({ fireSafetyCompliance: value })} /></div>
    <div className="rounded-2xl border border-[#E4E0E7] p-5"><h3 className="font-bold text-[#121B35] mb-3">Possession status <span className="text-[#F2C052]">*</span></h3><div className="flex gap-2 mb-3">{(["Ready to Move", "Under Construction"] as const).map((status) => <button type="button" key={status} onClick={() => choosePossession(status)} className={`px-3 py-2 rounded-lg text-[12px] border ${possession.status === status ? "bg-[#DDAA42] text-[#0B1328]" : "border-[#E4E0E7]"}`}>{status}</button>)}</div>{possession.status === "Under Construction" ? <Input label="Expected completion date" type="date" value={possession.expectedCompletionDate || ""} onChange={(value) => setPossession({ status: "Under Construction", expectedCompletionDate: value })} error={errors.possessionDate} /> : <Input label="Ready since" type="date" value={possession.launchDate || ""} onChange={(value) => setPossession({ status: "Ready to Move", launchDate: value })} error={errors.possessionDate} />}</div>
  </div>;
}
