import { useEffect, useState } from "react";
import { Archive, FileText, Loader2 } from "lucide-react";
import AdminLayout from "@/components/admin/AdminLayout";
import { fetchPropertyImportBatch, fetchPropertyImportBatches } from "@/lib/api";

type BatchRecord = { packageKey: string; packageName: string; projectName: string; status: string; property?: string; mediaCount: number; mediaBytes: number; documentCount: number; documentBytes: number; warnings?: string[]; error?: string };
type Batch = { id: string; name: string; status: string; packageCount: number; importedCount: number; skippedCount: number; failedCount: number; mediaCount: number; mediaBytes: number; documentCount: number; documentBytes: number; cloudinaryCreditsBefore?: number; cloudinaryCreditsAfter?: number; sharedReraNumbers?: Array<{ reraNumber: string; projects: string[] }>; records?: BatchRecord[]; updatedAt?: string };

function bytes(value = 0) { return value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(2)} GB` : `${(value / 1024 ** 2).toFixed(1)} MB`; }

export default function AdminBatchReports() {
  const [batches, setBatches] = useState<Batch[]>([]);
  const [selected, setSelected] = useState<Batch | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { fetchPropertyImportBatches().then((data) => setBatches(data.batches || [])).catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  const open = async (id: string) => { setLoading(true); setError(""); try { setSelected((await fetchPropertyImportBatch(id)).batch); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to open batch"); } finally { setLoading(false); } };
  return <AdminLayout><div className="mb-7"><h1 className="flex items-center gap-2 text-[28px] font-bold text-[#121B35]"><FileText className="size-7 text-[#B98428]" />Batch Reports</h1><p className="mt-1 text-sm text-[#68646F]">Import totals, Cloudinary usage, package status and errors are stored separately from property records.</p></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading && !batches.length ? <Loader2 className="mx-auto mt-20 size-7 animate-spin text-[#DDAA42]" /> : <div className="grid gap-5 xl:grid-cols-[340px_1fr]"><div className="space-y-3">{batches.map((batch) => <button key={batch.id} onClick={() => void open(batch.id)} className="w-full rounded-2xl border border-[#E4E0E7] bg-white p-4 text-left shadow-sm hover:border-[#DDAA42]"><div className="flex items-center gap-2"><Archive className="size-4 text-[#B98428]" /><strong className="text-sm text-[#121B35]">{batch.name}</strong><span className="ml-auto rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold uppercase text-blue-700">{batch.status}</span></div><p className="mt-2 text-xs text-[#68646F]">{batch.importedCount}/{batch.packageCount} imported · {batch.failedCount} failed</p></button>)}</div><div>{selected ? <div className="rounded-2xl border border-[#E4E0E7] bg-white p-5"><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Packages",selected.packageCount],["Imported",selected.importedCount],["Failed",selected.failedCount],["Media",selected.mediaCount],["Documents",selected.documentCount],["RERA conflicts",selected.sharedReraNumbers?.length || 0]].map(([label,value]) => <div key={String(label)} className="rounded-xl bg-[#F8F7FA] p-3"><p className="text-[10px] font-bold uppercase text-[#8A8690]">{label}</p><p className="mt-1 text-xl font-bold text-[#121B35]">{value}</p></div>)}</div><p className="mt-4 text-xs text-[#68646F]">Media {bytes(selected.mediaBytes)} · Documents {bytes(selected.documentBytes)} · Cloudinary credits {selected.cloudinaryCreditsBefore ?? "—"} → {selected.cloudinaryCreditsAfter ?? "—"}</p><div className="mt-4 max-h-[560px] overflow-auto rounded-xl border border-[#ECE9EF]">{(selected.records || []).map((record) => <div key={record.packageKey} className="grid gap-1 border-b border-[#F0EDF2] px-3 py-2 text-xs sm:grid-cols-[1fr_100px_180px]"><div><p className="font-bold text-[#121B35]">{record.projectName}</p><p className="truncate text-[10px] text-[#68646F]">{record.packageName}</p>{record.error && <p className="mt-1 text-[10px] text-red-700">{record.error}</p>}</div><span className="font-bold uppercase text-blue-700">{record.status}</span><span className="text-[#68646F]">{record.mediaCount || 0} media · {record.documentCount || 0} docs</span></div>)}</div></div> : <div className="rounded-2xl border border-dashed border-[#D8D3DA] p-12 text-center text-sm text-[#68646F]">Select a batch report.</div>}</div></div>}</AdminLayout>;
}
