import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Clock3, FileUp, Loader2, MessageCircle, PhoneCall, RefreshCw, Search, UserRoundCheck, UsersRound } from "lucide-react";
import AdminLayout from "@/components/admin/AdminLayout";
import { assignCRMPartner, createCRMTemplate, fetchAdminCRMPartner, fetchAdminCRMPartners, fetchCRMEmployees, fetchCRMTemplates, updateCRMTemplate, uploadCRMMaterial } from "@/lib/api";
import { stageLabels, type CRMAttachment, type CRMEmployee, type CRMPartner, type CRMPartnerDetail, type CRMStage, type CRMTemplate } from "@/lib/cpCrmTypes";

const stages: Array<"" | CRMStage> = ["", "new", "attempted", "callback", "interested", "has_clients", "not_interested", "do_not_contact"];
const blankTemplate = { name: "", kind: "project" as "project" | "follow_up", projectName: "", body: "Hello {{cp_name}},\n\nSharing details for {{project_name}}.\n\n{{material_links}}\n\nRegards,\n{{employee_name}}" };
const when = (value?: string | null) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not yet";

export default function AdminCPManagement() {
  const [view, setView] = useState<"partners" | "templates">("partners");
  const [partners, setPartners] = useState<CRMPartner[]>([]);
  const [employees, setEmployees] = useState<CRMEmployee[]>([]);
  const [templates, setTemplates] = useState<CRMTemplate[]>([]);
  const [selected, setSelected] = useState<CRMPartnerDetail | null>(null);
  const [search, setSearch] = useState("");
  const [stage, setStage] = useState("");
  const [employeeId, setEmployeeId] = useState("");
  const [templateForm, setTemplateForm] = useState(blankTemplate);
  const [attachments, setAttachments] = useState<CRMAttachment[]>([]);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  const loadReference = useCallback(async () => {
    try {
      const [employeeData, templateData] = await Promise.all([fetchCRMEmployees(), fetchCRMTemplates()]);
      setEmployees(employeeData.employees || []); setTemplates(templateData.templates || []);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load CRM controls."); }
  }, []);
  const loadPartners = useCallback(async () => {
    setBusy("partners"); setError("");
    try { const data = await fetchAdminCRMPartners({ search, stage, employeeId, limit: 100 }); setPartners(data.partners || []); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load Channel Partners."); }
    finally { setBusy(""); }
  }, [search, stage, employeeId]);
  useEffect(() => { void loadReference(); }, [loadReference]);
  useEffect(() => { const timer = window.setTimeout(() => void loadPartners(), 250); return () => window.clearTimeout(timer); }, [loadPartners]);

  const open = async (partnerId: string) => {
    setBusy(partnerId); setError("");
    try { setSelected(await fetchAdminCRMPartner(partnerId)); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to open CP details."); }
    finally { setBusy(""); }
  };
  const assign = async (partnerId: string, nextEmployeeId: string) => {
    setBusy("assign");
    try { await assignCRMPartner(partnerId, nextEmployeeId); setNotice(nextEmployeeId ? "Employee assignment updated." : "Channel Partner is now unassigned."); await loadPartners(); setSelected(await fetchAdminCRMPartner(partnerId)); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update assignment."); }
    finally { setBusy(""); }
  };
  const upload = async (file?: File) => {
    if (!file) return; setBusy("upload"); setError("");
    try { const item = await uploadCRMMaterial(file); setAttachments((items) => [...items, item]); setNotice(`${file.name} uploaded.`); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to upload material."); }
    finally { setBusy(""); }
  };
  const saveTemplate = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy("template"); setError("");
    try { await createCRMTemplate({ ...templateForm, attachments }); setTemplateForm(blankTemplate); setAttachments([]); setNotice("Message template created."); await loadReference(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save template."); }
    finally { setBusy(""); }
  };
  const toggleTemplate = async (template: CRMTemplate) => {
    setBusy(template.id);
    try { await updateCRMTemplate(template.id, { isActive: !template.isActive }); await loadReference(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update template."); }
    finally { setBusy(""); }
  };
  const counts = useMemo(() => partners.reduce((result, profile) => ({ ...result, [profile.stage]: (result[profile.stage] || 0) + 1 }), {} as Record<string, number>), [partners]);

  return <AdminLayout><div className="mx-auto max-w-[1500px] space-y-5 pb-12">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase text-[#9A7427]">Partner outreach</p><h1 className="mt-1 text-[30px] font-bold text-[#121B35]">CP Management</h1><p className="mt-1 text-[13px] text-[#68646F]">Assign registered partners, inspect employee activity, callbacks, and WhatsApp communication.</p></div><div className="flex rounded-md border border-[#D8D3DA] bg-white p-1"><button onClick={() => setView("partners")} className={`h-9 rounded px-3 text-xs font-bold ${view === "partners" ? "bg-[#121B35] text-white" : "text-[#68646F]"}`}>Partners</button><button onClick={() => setView("templates")} className={`h-9 rounded px-3 text-xs font-bold ${view === "templates" ? "bg-[#121B35] text-white" : "text-[#68646F]"}`}>Message templates</button></div></header>
    {error && <div role="alert" className="flex gap-2 rounded-md border border-red-200 bg-red-50 p-3 text-xs text-red-700"><AlertCircle className="size-4" />{error}</div>}{notice && <div role="status" className="flex gap-2 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700"><CheckCircle2 className="size-4" />{notice}</div>}
    {view === "partners" ? <>
      <section className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-[#E4E0E7] bg-[#E4E0E7] md:grid-cols-4"><Summary label="Visible CPs" value={partners.length} icon={UsersRound} /><Summary label="Callbacks" value={counts.callback || 0} icon={Clock3} /><Summary label="Interested" value={counts.interested || 0} icon={UserRoundCheck} /><Summary label="Have clients" value={counts.has_clients || 0} icon={CheckCircle2} /></section>
      <div className="grid gap-3 rounded-lg border border-[#E4E0E7] bg-white p-4 md:grid-cols-[minmax(220px,1fr)_180px_220px_40px]"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-[#8A8690]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search company, contact, phone, city..." className="h-10 w-full rounded-md border border-[#D8D3DA] pl-9 pr-3 text-xs" /></label><select value={stage} onChange={(event) => setStage(event.target.value)} className="h-10 rounded-md border border-[#D8D3DA] px-3 text-xs"><option value="">All stages</option>{stages.filter(Boolean).map((item) => <option key={item} value={item}>{stageLabels[item as CRMStage]}</option>)}</select><select value={employeeId} onChange={(event) => setEmployeeId(event.target.value)} className="h-10 rounded-md border border-[#D8D3DA] px-3 text-xs"><option value="">All employees</option><option value="unassigned">Unassigned</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select><button onClick={() => void loadPartners()} className="grid size-10 place-items-center rounded-md border border-[#D8D3DA]" title="Refresh"><RefreshCw className={`size-4 ${busy === "partners" ? "animate-spin" : ""}`} /></button></div>
      <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_450px]"><section className="overflow-hidden rounded-lg border border-[#E4E0E7] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-[#F8F7FA] text-[10px] uppercase text-[#68646F]"><tr><th className="px-4 py-3">Channel Partner</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Next callback</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-[#F0EDF1]">{partners.map((profile) => <tr key={profile.id} className={selected?.profile.partner.id === profile.partner.id ? "bg-[#FFF8E8]" : "hover:bg-[#FAF9FA]"}><td className="px-4 py-3"><strong className="block text-[13px] text-[#121B35]">{profile.partner.companyName}</strong><span className="text-[10px] text-[#8A8690]">{profile.partner.applicationNumber} · {profile.partner.city}</span></td><td className="px-4 py-3"><span className="block text-xs text-[#3F3D46]">{profile.partner.contactName}</span><span className="text-[11px] text-[#68646F]">{profile.partner.mobile}</span></td><td className="px-4 py-3 text-xs text-[#3F3D46]">{profile.assignedEmployee?.name || "Unassigned"}</td><td className="px-4 py-3"><Stage value={profile.stage} /></td><td className="px-4 py-3 text-[11px] text-[#3F3D46]">{when(profile.nextFollowUpAt)}</td><td className="px-4 py-3"><button onClick={() => void open(profile.partner.id)} className="rounded-md border border-[#D8D3DA] px-2.5 py-1.5 text-[11px] font-bold text-[#121B35]">View</button></td></tr>)}{!partners.length && busy !== "partners" && <tr><td colSpan={6} className="p-10 text-center text-sm text-[#68646F]">No partners match this view.</td></tr>}</tbody></table></div></section>
        <aside className="rounded-lg border border-[#E4E0E7] bg-white p-5 xl:sticky xl:top-20">{busy && busy !== "partners" && !selected ? <Loader2 className="mx-auto my-12 size-6 animate-spin text-[#DDAA42]" /> : selected ? <AdminPartnerDetail detail={selected} employees={employees} busy={busy === "assign"} onAssign={assign} /> : <div className="py-12 text-center"><UsersRound className="mx-auto size-8 text-[#C9C5CD]" /><p className="mt-2 text-xs text-[#68646F]">Select a Channel Partner to view all employee activity.</p></div>}</aside>
      </div>
    </> : <div className="grid items-start gap-5 xl:grid-cols-[440px_minmax(0,1fr)]"><form onSubmit={saveTemplate} className="rounded-lg border border-[#E4E0E7] bg-white p-5"><h2 className="text-sm font-bold text-[#121B35]">Create WhatsApp template</h2><p className="mt-1 text-[11px] text-[#68646F]">Use: {"{{cp_name}}, {{company_name}}, {{project_name}}, {{employee_name}}, {{material_links}}"}</p><div className="mt-4 space-y-3"><Input label="Template name" value={templateForm.name} onChange={(value) => setTemplateForm({ ...templateForm, name: value })} /><label className="block"><span className="text-[10px] font-bold uppercase text-[#68646F]">Message type</span><select value={templateForm.kind} onChange={(event) => setTemplateForm({ ...templateForm, kind: event.target.value as "project" | "follow_up" })} className="mt-1 h-10 w-full rounded-md border border-[#D8D3DA] px-3 text-xs"><option value="project">Project message</option><option value="follow_up">Follow-up message</option></select></label><Input label="Project name" value={templateForm.projectName} onChange={(value) => setTemplateForm({ ...templateForm, projectName: value })} /><label className="block"><span className="text-[10px] font-bold uppercase text-[#68646F]">Message</span><textarea value={templateForm.body} onChange={(event) => setTemplateForm({ ...templateForm, body: event.target.value })} className="mt-1 h-44 w-full resize-y rounded-md border border-[#D8D3DA] p-3 text-xs leading-5" /></label><label className="flex h-11 cursor-pointer items-center justify-center gap-2 rounded-md border border-dashed border-[#BDB7C2] bg-[#F8F7FA] text-xs font-bold text-[#3F3D46]"><FileUp className="size-4" />{busy === "upload" ? "Uploading..." : "Add photo or PDF"}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="sr-only" disabled={busy === "upload"} onChange={(event) => void upload(event.target.files?.[0])} /></label>{attachments.map((item, index) => <div key={`${item.url}-${index}`} className="flex items-center justify-between rounded-md bg-[#F8F7FA] px-3 py-2 text-[11px]"><span className="truncate">{item.title}</span><button type="button" onClick={() => setAttachments((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="font-bold text-red-700">Remove</button></div>)}</div><button disabled={busy === "template" || !templateForm.name.trim() || !templateForm.body.trim()} className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded-md bg-[#DDAA42] text-xs font-bold text-[#121B35] disabled:opacity-40">{busy === "template" ? <Loader2 className="size-4 animate-spin" /> : <MessageCircle className="size-4" />}Save template</button></form>
      <section className="overflow-hidden rounded-lg border border-[#E4E0E7] bg-white"><div className="border-b border-[#E4E0E7] px-5 py-4"><h2 className="text-sm font-bold text-[#121B35]">Available templates</h2></div><div className="divide-y divide-[#F0EDF1]">{templates.map((template) => <article key={template.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="text-[13px] font-bold text-[#121B35]">{template.name}</h3><span className="rounded bg-[#F1F4FA] px-2 py-0.5 text-[9px] font-bold uppercase text-[#273559]">{template.kind.replace("_", " ")}</span></div><p className="mt-1 text-[11px] text-[#68646F]">{template.projectName || "General message"} · {template.attachments.length} material(s)</p></div><button onClick={() => void toggleTemplate(template)} disabled={busy === template.id} className={`rounded px-2.5 py-1.5 text-[10px] font-bold ${template.isActive ? "bg-emerald-50 text-emerald-700" : "bg-[#F0EDF1] text-[#68646F]"}`}>{template.isActive ? "Active" : "Disabled"}</button></div><pre className="mt-3 whitespace-pre-wrap rounded-md bg-[#F8F7FA] p-3 font-sans text-[11px] leading-5 text-[#3F3D46]">{template.body}</pre>{template.attachments.length > 0 && <div className="mt-2 flex flex-wrap gap-2">{template.attachments.map((item) => <a key={item._id || item.url} href={item.url} target="_blank" rel="noreferrer" className="rounded border border-[#D8D3DA] px-2 py-1 text-[10px] font-bold text-[#805A0B]">{item.title}</a>)}</div>}</article>)}{!templates.length && <p className="p-10 text-center text-sm text-[#68646F]">No templates yet.</p>}</div></section></div>}
  </div></AdminLayout>;
}

function AdminPartnerDetail({ detail, employees, busy, onAssign }: { detail: CRMPartnerDetail; employees: CRMEmployee[]; busy: boolean; onAssign: (partnerId: string, employeeId: string) => Promise<void> }) {
  const profile = detail.profile;
  return <div><p className="text-[10px] font-bold uppercase text-[#9A7427]">{profile.partner.applicationNumber}</p><h2 className="mt-1 text-lg font-bold text-[#121B35]">{profile.partner.companyName}</h2><p className="mt-1 text-xs text-[#68646F]">{profile.partner.contactName} · {profile.partner.mobile}<br/>{profile.partner.email}<br/>{profile.partner.city}, {profile.partner.state}</p><div className="mt-3 flex items-center gap-2"><Stage value={profile.stage} /><span className="text-[10px] text-[#68646F]">{detail.clientsCount} registered client(s)</span></div><label className="mt-4 block"><span className="text-[10px] font-bold uppercase text-[#68646F]">Assigned employee</span><select disabled={busy} value={profile.assignedEmployeeId} onChange={(event) => void onAssign(profile.partner.id, event.target.value)} className="mt-1 h-10 w-full rounded-md border border-[#D8D3DA] px-3 text-xs"><option value="">Unassigned</option>{employees.filter((employee) => employee.isActive).map((employee) => <option key={employee.id} value={employee.id}>{employee.name} ({employee.employeeId})</option>)}</select></label><div className="mt-5 grid grid-cols-3 gap-px overflow-hidden rounded-md bg-[#E4E0E7]"><Small label="Calls" value={profile.completedCalls} /><Small label="WA opened" value={profile.whatsappOpened} /><Small label="WA sent" value={profile.whatsappSent} /></div>{detail.followUps.length > 0 && <section className="mt-5"><h3 className="text-[10px] font-bold uppercase text-[#68646F]">Callbacks</h3><div className="mt-2 space-y-2">{detail.followUps.slice(0, 5).map((item) => <div key={item.id} className="rounded-md border border-[#E4E0E7] p-3"><div className="flex justify-between gap-2"><strong className="text-[11px] text-[#121B35]">{when(item.scheduledAt)}</strong><span className={`text-[9px] font-bold uppercase ${item.status === "pending" ? "text-amber-700" : "text-emerald-700"}`}>{item.status}</span></div>{item.note && <p className="mt-1 text-[10px] text-[#68646F]">{item.note}</p>}</div>)}</div></section>}<section className="mt-5"><h3 className="text-[10px] font-bold uppercase text-[#68646F]">Activity history</h3><div className="mt-2 max-h-[340px] space-y-2 overflow-y-auto pr-1">{detail.interactions.map((item) => <div key={item.id} className="border-l-2 border-[#DDAA42] py-1 pl-3"><div className="flex items-center gap-1.5">{item.action.startsWith("call") ? <PhoneCall className="size-3 text-[#805A0B]" /> : <MessageCircle className="size-3 text-[#805A0B]" />}<strong className="text-[11px] capitalize text-[#121B35]">{item.action.replace(/_/g, " ")}{item.outcome ? ` · ${item.outcome.replace(/_/g, " ")}` : ""}</strong></div>{item.note && <p className="mt-1 text-[10px] text-[#68646F]">{item.note}</p>}<p className="mt-1 text-[9px] text-[#96909A]">{item.employee?.name || "Employee"} · {when(item.createdAt)}</p></div>)}{!detail.interactions.length && <p className="text-xs text-[#68646F]">No employee activity yet.</p>}</div></section></div>;
}

function Summary({ label, value, icon: Icon }: { label: string; value: number; icon: typeof UsersRound }) { return <div className="bg-white p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase text-[#68646F]">{label}</span><Icon className="size-4 text-[#9A7427]" /></div><strong className="mt-2 block text-2xl text-[#121B35]">{value}</strong></div>; }
function Small({ label, value }: { label: string; value: number }) { return <div className="bg-[#F8F7FA] p-2.5 text-center"><strong className="block text-sm text-[#121B35]">{value}</strong><span className="text-[8px] font-bold uppercase text-[#68646F]">{label}</span></div>; }
function Stage({ value }: { value: CRMStage }) { const tone = value === "has_clients" || value === "interested" ? "bg-emerald-50 text-emerald-700" : value === "callback" ? "bg-amber-50 text-amber-800" : value === "not_interested" || value === "do_not_contact" ? "bg-red-50 text-red-700" : "bg-[#F1F4FA] text-[#273559]"; return <span className={`inline-flex rounded px-2 py-1 text-[10px] font-bold ${tone}`}>{stageLabels[value]}</span>; }
function Input({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block"><span className="text-[10px] font-bold uppercase text-[#68646F]">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-[#D8D3DA] px-3 text-xs" /></label>; }
