import AdminLayout from "@/components/admin/AdminLayout";
import { createAdminCampaign, downloadLocalCampaignMedia, fetchAdminCampaignContacts, fetchAllAdminCampaignContactIds, fetchAdminCampaigns, fetchAdminCampaign, updateAdminCampaignRecipient, uploadLocalCampaignMedia } from "@/lib/api";
import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, FileUp, Loader2, MessageCircle, RefreshCw, Search, UsersRound } from "lucide-react";

type Contact = { id: string; name: string; company: string; mobile: string; whatsappMobile: string; whatsappUrl: string; city: string; state: string; pincode: string; areas: string[]; status: string };
type Attachment = { title: string; url: string; mimeType?: string; bytes?: number };
type Batch = { name: string; senderNumber: string; message: string; projectDetails: string; attachments: Attachment[]; recipientIds: string[] };
const emptyBatch = (index: number): Batch => ({ name: `Batch ${index + 1}`, senderNumber: "", message: "", projectDetails: "", attachments: [], recipientIds: [] });

export default function AdminCPCampaigns() {
  const [contacts, setContacts] = useState<Contact[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set()); const [batches, setBatches] = useState<Batch[]>([0, 1, 2, 3].map(emptyBatch));
  const [name, setName] = useState(""); const [search, setSearch] = useState(""); const [state, setState] = useState(""); const [city, setCity] = useState(""); const [area, setArea] = useState(""); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ page: 1, pages: 1, total: 0 });
  const [areas, setAreas] = useState<string[]>([]); const [cities, setCities] = useState<string[]>([]); const [states, setStates] = useState<string[]>([]); const [campaigns, setCampaigns] = useState<any[]>([]); const [openCampaign, setOpenCampaign] = useState<any>(null);
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const assignedIds = useMemo(() => new Set(batches.flatMap((batch) => batch.recipientIds)), [batches]);
  const loadContacts = async () => { setBusy("contacts"); setError(""); try { const data = await fetchAdminCampaignContacts({ page, limit: 100, search, state, city, area }); setContacts(data.contacts || []); setPagination(data.pagination); setAreas(data.areas || []); setCities(data.cities || []); setStates(data.states || []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load contacts."); } finally { setBusy(""); } };
  const loadCampaigns = async () => { try { const data = await fetchAdminCampaigns(); setCampaigns(data.campaigns || []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load campaigns."); } };
  useEffect(() => { const timer = window.setTimeout(() => void loadContacts(), 250); return () => window.clearTimeout(timer); }, [page, search, state, city, area]);
  useEffect(() => { void loadCampaigns(); }, []);
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const selectAllMatching = async () => { setBusy("select-all"); setError(""); try { const data = await fetchAllAdminCampaignContactIds({ search, state, city, area }); setSelected(new Set(data.ids || [])); setNotice(`${Number(data.total || 0).toLocaleString("en-IN")} matching contact(s) selected across all pages.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to select all matching contacts."); } finally { setBusy(""); } };
  const moveSelected = (batchIndex: number) => { if (!selected.size) return; setBatches((current) => current.map((batch, index) => ({ ...batch, recipientIds: index === batchIndex ? [...new Set([...batch.recipientIds, ...selected])] : batch.recipientIds.filter((id) => !selected.has(id)) }))); setSelected(new Set()); setNotice(`${selected.size} contact(s) moved to ${batches[batchIndex].name}.`); };
  const updateBatch = (index: number, patch: Partial<Batch>) => setBatches((current) => current.map((batch, batchIndex) => batchIndex === index ? { ...batch, ...patch } : batch));
  const upload = async (index: number, file?: File) => { if (!file) return; setBusy(`upload-${index}`); try { const item = await uploadLocalCampaignMedia(file); updateBatch(index, { attachments: [...batches[index].attachments, { ...item, title: item.title || item.originalName || file.name }] }); setNotice(`${file.name} saved on the local campaign server.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save file locally."); } finally { setBusy(""); } };
  const save = async () => { setBusy("save"); setError(""); try { const result = await createAdminCampaign({ name, filters: { state, city, area, search }, batches }); setNotice(`Draft saved with ${result.recipientCount} recipient(s).`); setName(""); setBatches([0, 1, 2, 3].map(emptyBatch)); setSelected(new Set()); await loadCampaigns(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save campaign."); } finally { setBusy(""); } };
  const openNext = async (campaign: any, recipient: any) => { if (!recipient?.prospectId?.whatsappUrl) return; await updateAdminCampaignRecipient(campaign.id, recipient.id, { status: "opened" }); window.open(`${recipient.prospectId.whatsappUrl}?text=${encodeURIComponent(recipient.message || "")}`, "_blank", "noopener,noreferrer"); setOpenCampaign({ ...openCampaign, recipients: openCampaign.recipients.map((item: any) => item.id === recipient.id ? { ...item, status: "opened" } : item) }); };
  const loadCampaign = async (id: string) => { setBusy(`campaign-${id}`); try { setOpenCampaign(await fetchAdminCampaign(id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to open campaign."); } finally { setBusy(""); } };
  const updateStatus = async (recipient: any, status: string) => { await updateAdminCampaignRecipient(openCampaign.campaign.id, recipient.id, { status }); setOpenCampaign({ ...openCampaign, recipients: openCampaign.recipients.map((item: any) => item.id === recipient.id ? { ...item, status } : item) }); };

  return <AdminLayout><div className="mx-auto max-w-[1600px] space-y-5 pb-12"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase text-[#9A7427]">Admin only · CP outreach</p><h1 className="mt-1 text-[30px] font-bold text-[#121B35]">Area Campaigns</h1><p className="mt-1 text-[13px] text-[#68646F]">Analyze existing contacts, manually divide them into four batches, prepare drafts, and review WhatsApp sending.</p></div><button onClick={() => { void loadContacts(); void loadCampaigns(); }} className="grid size-10 place-items-center rounded-md border border-[#D8D3DA] bg-white"><RefreshCw className={`size-4 ${busy === "contacts" ? "animate-spin" : ""}`} /></button></header>
    {error && <div role="alert" className="flex gap-2 rounded-md border border-red-200 bg-red-50 p-3 text-xs text-red-700"><AlertCircle className="size-4" />{error}</div>}{notice && <div role="status" className="flex gap-2 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700"><CheckCircle2 className="size-4" />{notice}</div>}
    <section className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-[#E4E0E7] bg-[#E4E0E7] md:grid-cols-4"><Metric label="Matching contacts" value={pagination.total} /><Metric label="Selected" value={selected.size + assignedIds.size} /><Metric label="Batch 1" value={batches[0].recipientIds.length} /><Metric label="Batch 2–4" value={batches.slice(1).reduce((sum, batch) => sum + batch.recipientIds.length, 0)} /></section>
    <section className="rounded-lg border border-[#E4E0E7] bg-white p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="relative xl:col-span-2"><Search className="absolute left-3 top-3 size-4 text-[#8A8690]" /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search name, company, phone, location..." className="h-10 w-full rounded-md border border-[#D8D3DA] pl-9 pr-3 text-xs" /></label><select value={state} onChange={(event) => { setState(event.target.value); setPage(1); }} className="h-10 rounded-md border border-[#D8D3DA] px-3 text-xs"><option value="">All states</option>{states.map((item) => <option key={item}>{item}</option>)}</select><select value={city} onChange={(event) => { setCity(event.target.value); setPage(1); }} className="h-10 rounded-md border border-[#D8D3DA] px-3 text-xs"><option value="">All cities</option>{cities.map((item) => <option key={item}>{item}</option>)}</select><select value={area} onChange={(event) => { setArea(event.target.value); setPage(1); }} className="h-10 rounded-md border border-[#D8D3DA] px-3 text-xs"><option value="">All areas</option>{areas.map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><button onClick={() => void selectAllMatching()} disabled={busy === "select-all" || !pagination.total} className="h-9 rounded-md border border-[#DDAA42] px-3 text-[10px] font-bold text-[#805A0B] disabled:opacity-35">{busy === "select-all" ? "Selecting..." : `Select all ${pagination.total.toLocaleString("en-IN")} matching`}</button><button onClick={() => setSelected(new Set())} disabled={!selected.size} className="h-9 rounded-md border px-3 text-[10px] font-bold disabled:opacity-35">Clear selection</button><span className="self-center text-[11px] text-[#68646F]">Selected: {selected.size}</span></div><div className="flex flex-wrap gap-2"><span className="self-center text-[11px] text-[#68646F]">Select contacts, then move them into a batch.</span>{batches.map((batch, index) => <button key={batch.name} onClick={() => moveSelected(index)} disabled={!selected.size} className="h-9 rounded-md bg-[#121B35] px-3 text-[10px] font-bold text-white disabled:opacity-35">Move to {batch.name} ({batch.recipientIds.length})</button>)}</div></div></section>
    <section className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_560px]"><div className="overflow-hidden rounded-lg border border-[#E4E0E7] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-[#F8F7FA] text-[10px] uppercase text-[#68646F]"><tr><th className="w-10 px-4 py-3"></th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Area</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Batch</th></tr></thead><tbody className="divide-y divide-[#F0EDF1]">{contacts.map((contact) => { const batch = batches.find((item) => item.recipientIds.includes(contact.id)); const checked = selected.has(contact.id); return <tr key={contact.id} className={checked ? "bg-[#FFF8E8]" : ""}><td className="px-4 py-3"><input type="checkbox" checked={checked} onChange={() => toggle(contact.id)} /></td><td className="px-4 py-3"><strong className="block text-[#121B35]">{contact.name}</strong><span className="text-[10px] text-[#68646F]">{contact.company || "No company"} · {contact.whatsappMobile || contact.mobile}</span></td><td className="px-4 py-3">{contact.areas.join(", ") || "Area not collected"}<span className="block text-[10px] text-[#8A8690]">{contact.city}, {contact.state}</span></td><td className="px-4 py-3">{contact.status}</td><td className="px-4 py-3 text-[10px] font-bold">{batch?.name || "Not assigned"}</td></tr>; })}{!contacts.length && <tr><td colSpan={5} className="p-12 text-center text-sm text-[#68646F]">No contacts match this location.</td></tr>}</tbody></table></div><div className="flex items-center justify-between border-t border-[#E4E0E7] px-4 py-3 text-xs"><span>{pagination.total.toLocaleString("en-IN")} matching contacts · page {pagination.page} / {pagination.pages}</span><div className="flex gap-2"><button disabled={page <= 1 || busy === "contacts"} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1.5 disabled:opacity-35">Previous</button><button disabled={page >= pagination.pages || busy === "contacts"} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1.5 disabled:opacity-35">Next</button></div></div></div>
      <div className="space-y-4"><section className="rounded-lg border border-[#E4E0E7] bg-white p-4"><h2 className="text-sm font-bold text-[#121B35]">Manual four-batch setup</h2><p className="mt-1 text-[11px] text-[#68646F]">Assign contacts manually. Each batch can use a different sender number, message, and media.</p><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Campaign name" className="mt-3 h-10 w-full rounded-md border border-[#D8D3DA] px-3 text-xs" />{batches.map((batch, index) => <BatchEditor key={batch.name} batch={batch} index={index} busy={busy} onChange={updateBatch} onUpload={upload} />)}<button onClick={() => void save()} disabled={busy === "save" || !name.trim() || !batches.some((batch) => batch.recipientIds.length)} className="mt-3 inline-flex h-11 w-full items-center justify-center gap-2 rounded-md bg-[#DDAA42] text-xs font-bold text-[#121B35] disabled:opacity-40">{busy === "save" ? <Loader2 className="size-4 animate-spin" /> : <MessageCircle className="size-4" />}Save campaign drafts</button></section>
      <section className="rounded-lg border border-[#E4E0E7] bg-white"><div className="border-b border-[#E4E0E7] px-4 py-3"><h2 className="text-sm font-bold text-[#121B35]">Saved campaigns</h2></div>{campaigns.map((campaign) => <button key={campaign.id} onClick={() => void loadCampaign(campaign.id)} className="block w-full border-b border-[#F0EDF1] p-4 text-left hover:bg-[#FAF9FA]"><strong className="block text-xs text-[#121B35]">{campaign.name}</strong><span className="mt-1 block text-[10px] text-[#68646F]">{campaign.batches.map((batch: any) => `${batch.name}: ${batch.recipientCount}`).join(" · ")}</span></button>)}{!campaigns.length && <p className="p-8 text-center text-xs text-[#68646F]">No campaigns saved yet.</p>}</section></div></section>
    {openCampaign && <CampaignDetail campaign={openCampaign} onClose={() => setOpenCampaign(null)} onOpen={openNext} onStatus={updateStatus} />}
  </div></AdminLayout>;
}

function BatchEditor({ batch, index, busy, onChange, onUpload }: { batch: Batch; index: number; busy: string; onChange: (index: number, patch: Partial<Batch>) => void; onUpload: (index: number, file?: File) => void }) { const craft = () => onChange(index, { message: `Hello {{contact_name}},\n\n${batch.projectDetails.trim() || "Sharing the project details with you."}\n\nPlease review the attached documents and video. Reply if you would like more details.\n\nRegards,\nClearTitle One` }); return <article className="mt-3 rounded-md border border-[#E4E0E7] p-3"><div className="flex items-center justify-between gap-2"><strong className="text-xs text-[#121B35]">{batch.name}</strong><span className="text-[10px] font-bold text-[#805A0B]">{batch.recipientIds.length} contacts</span></div><div className="mt-2 grid grid-cols-2 gap-2"><input value={batch.name} onChange={(event) => onChange(index, { name: event.target.value })} className="h-9 rounded border px-2 text-[11px]" placeholder="Batch name" /><input value={batch.senderNumber} onChange={(event) => onChange(index, { senderNumber: event.target.value })} className="h-9 rounded border px-2 text-[11px]" placeholder="WhatsApp sender number" /></div><textarea value={batch.projectDetails} onChange={(event) => onChange(index, { projectDetails: event.target.value })} placeholder="Project details for Craft Message..." className="mt-2 h-16 w-full resize-y rounded border p-2 text-[11px]" /><button type="button" onClick={craft} className="mt-2 h-8 rounded border border-[#DDAA42] px-3 text-[10px] font-bold text-[#805A0B]">Craft Message</button><textarea value={batch.message} onChange={(event) => onChange(index, { message: event.target.value })} placeholder="Message for this batch..." className="mt-2 h-20 w-full resize-y rounded border p-2 text-[11px]" /><label className="mt-2 flex h-9 cursor-pointer items-center justify-center gap-2 rounded border border-dashed text-[10px] font-bold"><FileUp className="size-3" />{busy === `upload-${index}` ? "Uploading..." : "Add PDF, image, or video (max 200 MB)"}<input type="file" accept="application/pdf,image/*,video/*,.mp4,.webm,.mov,.m4v,.mkv,.avi" className="sr-only" disabled={busy === `upload-${index}`} onChange={(event) => void onUpload(index, event.target.files?.[0])} /></label>{batch.attachments.map((file, fileIndex) => <div key={`${file.url}-${fileIndex}`} className="mt-1 truncate text-[10px] text-[#68646F]">{file.title}</div>)}</article>; }
function CampaignDetail({ campaign, onClose, onOpen, onStatus }: { campaign: any; onClose: () => void; onOpen: (campaign: any, recipient: any) => Promise<void>; onStatus: (recipient: any, status: string) => Promise<void> }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/30 p-4"><section className="mx-auto max-w-5xl rounded-lg bg-white p-5 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold text-[#121B35]">{campaign.campaign.name}</h2><p className="mt-1 text-xs text-[#68646F]">Review each draft, download original files, open the correct WhatsApp number, then mark the result.</p></div><button onClick={onClose} className="rounded border px-3 py-1 text-xs">Close</button></div><div className="mt-4 space-y-2">{campaign.recipients.map((recipient: any) => <div key={recipient.id} className="grid gap-2 rounded border p-3 md:grid-cols-[1fr_100px_220px]"><div><strong className="text-xs">{recipient.prospectId?.name || "Contact"}</strong><span className="ml-2 text-[10px] text-[#68646F]">{recipient.prospectId?.whatsappMobile || recipient.prospectId?.mobile}</span><p className="mt-1 whitespace-pre-wrap text-[10px] text-[#68646F]">{recipient.message}</p><p className="mt-1 text-[10px] text-[#8A8690]">{recipient.attachments?.length || 0} original attachment(s) · Sender: {recipient.senderNumber || "Not set"}</p><div className="mt-2 flex flex-wrap gap-1">{(recipient.attachments || []).map((file: any) => <button key={file.url} onClick={() => void downloadLocalCampaignMedia(file.url, file.title)} className="rounded border border-[#D8D3DA] px-2 py-1 text-[10px] font-bold text-[#805A0B]">Download {file.title}</button>)}</div></div><span className="self-start rounded bg-[#F1F4FA] px-2 py-1 text-center text-[10px] font-bold capitalize">{recipient.status}</span><div className="flex flex-wrap items-start justify-end gap-2"><button disabled={!recipient.prospectId?.whatsappUrl} onClick={() => void onOpen(campaign, recipient)} className="inline-flex h-8 items-center gap-1 rounded bg-[#168B52] px-2.5 text-[10px] font-bold text-white disabled:opacity-40"><MessageCircle className="size-3" />Open WhatsApp</button>{["sent", "failed", "skipped", "pending"].map((status) => <button key={status} onClick={() => void onStatus(recipient, status)} className="h-8 rounded border px-2 text-[10px] font-bold capitalize">{status}</button>)}</div></div>)}</div></section></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="bg-white p-4"><span className="text-[9px] font-bold uppercase text-[#68646F]">{label}</span><strong className="mt-1 block text-2xl text-[#121B35]">{value.toLocaleString("en-IN")}</strong></div>; }
