import { useEffect, useState } from "react";
import { FileWarning, Loader2, Pencil } from "lucide-react";
import AdminLayout from "@/components/admin/AdminLayout";
import Link from "@/components/Link";
import { fetchPropertyImportReraConflicts } from "@/lib/api";

type ConflictProperty = { id: string; title: string; builder?: string; locality?: { city?: string; address?: string }; reraNumber?: string; bulkImport?: { packageName?: string } };
type Conflict = { batchId: string; batchName: string; reraNumber: string; projectNames: string[]; properties: ConflictProperty[] };

export default function AdminReraConflicts() {
  const [conflicts, setConflicts] = useState<Conflict[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetchPropertyImportReraConflicts().then((data) => setConflicts(data.conflicts || [])).catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  return <AdminLayout><div className="mb-7"><h1 className="flex items-center gap-2 text-[28px] font-bold text-[#121B35]"><FileWarning className="size-7 text-amber-700" />RERA Conflicts</h1><p className="mt-1 text-sm text-[#68646F]">Repeated RERA numbers are shown side by side. Projects remain separate and are never merged automatically.</p></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading ? <Loader2 className="mx-auto mt-20 size-7 animate-spin text-[#DDAA42]" /> : conflicts.length === 0 ? <div className="rounded-2xl border border-dashed p-12 text-center text-sm text-[#68646F]">No repeated RERA numbers found.</div> : <div className="space-y-5">{conflicts.map((conflict) => <section key={`${conflict.batchId}-${conflict.reraNumber}`} className="rounded-2xl border border-amber-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-[10px] font-bold uppercase text-amber-700">Repeated RERA number</p><h2 className="mt-1 font-mono text-sm font-bold text-[#121B35]">{conflict.reraNumber}</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">{conflict.projectNames.length} projects</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{conflict.projectNames.map((name) => { const property=conflict.properties.find((item) => item.title === name); return <article key={name} className="rounded-xl border border-[#ECE9EF] p-4"><h3 className="font-bold text-[#121B35]">{name}</h3><p className="mt-1 text-xs text-[#68646F]">{property?.builder || "Builder not supplied"} · {property?.locality?.city || "Location not supplied"}</p><p className="mt-1 truncate text-[10px] text-blue-700">{property?.bulkImport?.packageName || "Import record awaiting creation"}</p>{property ? <Link href={`/admin/post?edit=${encodeURIComponent(property.id)}`} className="mt-3 inline-flex items-center gap-1 rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700"><Pencil className="size-3.5" />Review and correct</Link> : <p className="mt-3 text-xs text-amber-700">Property import is not complete yet.</p>}</article>; })}</div></section>)}</div>}</AdminLayout>;
}
